#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# shell script to create Bacula SQLite tables

bindir=/usr/bin
PATH=$bindir:$PATH
cd /var/spool/bacula
db_name=bacula

sqlite3 $* ${db_name}.db <<END-OF-DATA
END-OF-DATA
exit 0
