#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# shell script to Delete the SQLite Bacula database (same as deleting 
#  the tables)
#
db_name=bacula

rm -f /var/spool/bacula/${db_name}.db
