#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# shell script to drop Bacula database(s)
#

bindir=/usr/bin
db_name=bacula

$bindir/mysql $* -f <<END-OF-DATA
  DROP DATABASE ${db_name};
END-OF-DATA
if test $? -eq 0 ; then
  echo "Drop of ${db_name} database succeeded."
else
  echo "Drop of ${db_name} database failed."
fi
exit 0
